apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv/hostpath-dags-pv.yaml
  - pv/hostpath-plugins-pv.yaml
  - pvc/hostpath-dags-pvc.yaml
  - pvc/hostpath-plugins-pvc.yaml