kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./dags
    containerPath: /opt/airflow/dags
    propagation: HostToContainer
  - hostPath: ./plugins
    containerPath: /opt/airflow/plugins
    propagation: HostToContainer
- role: worker
  extraMounts:
  - hostPath: ./dags
    containerPath: /opt/airflow/dags
    propagation: HostToContainer
  - hostPath: ./plugins
    containerPath: /opt/airflow/plugins
    propagation: HostToContainer
